apiVersion: v1
kind: Secret
metadata:
  name: vietsign-secret
type: Opaque
stringData:
  DB_PASSWORD: "jin5628376423"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vietsign-config
spec:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "vietsign_db"
  API_URL: "http://api.vietsign.com" # URL cho FE gọi tới BE
