apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.js: |
    window.ENV = {
      NEXT_PUBLIC_API_ROOT: "https://vietsign.ibme.edu.vn/user-service",
      NEXT_PUBLIC_API_ROOT_NODE: "https://vietsign.ibme.edu.vn/user-service",
      NEXT_PUBLIC_SUPABASE_URL: "https://yquscrbjluhkeslhagnz.supabase.co",
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY: "sb_publishable_UrRQWweNkHXcHz4yg6olUg_3QKdjxi4"
    };
